apiVersion: v1
kind: Secret
metadata:
  name: { { .Values.secret.name } }
type: Opaque
stringData:
  jira-url: { { .Values.secret.jiraUrl | quote } }
  jira-email: { { .Values.secret.jiraEmail | quote } }
  jira-token: { { .Values.secret.jiraToken | quote } }
  git-token: { { .Values.secret.gitToken | quote } }
